Notebook prepared by Muhammad Sohail Abbas sohail.abbas@isb.nu.edu.pk

# The Neuron Gorge
# https://sites.google.com/view/theneurongorge 

# PAI Lab 04

## Outline
* Numpy

## File Reading

The key function for working with files in Python is the open() function.

The open() function takes two parameters; filename, and mode.

In addition you can specify if the file should be handled as binary or text mode

"t" - Text - Default value. Text mode


In [23]:
f = open("Strings.txt")

In [28]:
f = open("Strings.txt", "rt")

Because "r" for read, and "t" for text are the default values, you do not need to specify them.

In [43]:
f = open("Strings.txt", "rt",encoding="utf-8")
text = []
# loop through each line
for line in f.readlines():
    text.append(line.strip())
    
print(text[:5])

['A', '', '', '', 'A-  prefix (also an- before a vowel sound) not, without (amoral). [greek]']


For File writing and deletion visit [Documentation](https://www.w3schools.com/python/python_file_write.asp)

# Numpy

Numpy is the core library for scientific computing in Python. It
provides a high-performance multidimensional array object, and tools for
working with these arrays.
To use Numpy, we first need to import the `numpy` package. By
convention, we import it using the alias `np`. Then, when we want to use
modules or functions in this library, we preface them with `np.`

In [4]:
pip install numpy # conda install numpy

Note: you may need to restart the kernel to use updated packages.


ERROR: Invalid requirement: '#'


In [1]:
import numpy as np

## Numpy Arrays

A numpy array is a grid of values, all of the same type, and is indexed
by a tuple of nonnegative integers. The number of dimensions is the rank
of the array; the shape of an array is a tuple of integers giving the
size of the array along each dimension.
We can create a `numpy` array by passing a Python list to `np.array()`.

In [4]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(a)

[1 2 3]


This creates the array we can see on the right here:

![](http://jalammar.github.io/images/numpy/create-numpy-array-1.png)

In [49]:
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


To create a `numpy` array with more dimensions, we can pass nested
lists, like this:

![](http://jalammar.github.io/images/numpy/numpy-array-create-2d.png)

![](http://jalammar.github.io/images/numpy/numpy-3d-array.png)

In [5]:
b = np.array([[1,2],[3,4]])   # Create a rank 2 array
print(b)

[[1 2]
 [3 4]]


In [10]:
b[1][1]

4

In [11]:
print(b.shape)

(2, 2)


There are often cases when we want numpy to initialize the values of the
array for us. numpy provides methods like `ones()`, `zeros()`, and
`random.random()` for these cases. We just pass them the number of
elements we want it to generate:

![](http://jalammar.github.io/images/numpy/create-numpy-array-ones-zeros-random.png)

We can also use these methods to produce multi-dimensional arrays, as
long as we pass them a tuple describing the dimensions of the matrix we
want to create:

![](http://jalammar.github.io/images/numpy/numpy-matrix-ones-zeros-random.png)

![](http://jalammar.github.io/images/numpy/numpy-3d-array-creation.png)

Sometimes, we need an array of a specific shape with “placeholder”
values that we plan to fill in with the result of a computation. The
`zeros` or `ones` functions are handy for this:

In [55]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [57]:
b = np.ones((1,2,3))   # Create an array of all ones
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [14]:
c = np.full((2,2), 10)
print(c)

[[10 10]
 [10 10]]


In [61]:
d = np.eye(3)        # Create a 2x2 identity matrix
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [67]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.72756775 0.30853502]
 [0.16648583 0.5358984 ]]


Numpy also has two useful functions for creating sequences of numbers:
`arange` and `linspace`.

The `arange` function accepts three arguments, which define the start
value, stop value of a half-open interval, and step size. (The default
step size, if not explicitly specified, is 1; the default start value,
if not explicitly specified, is 0.)

The `linspace` function is similar, but we can specify the number of
values instead of the step size, and it will create a sequence of evenly
spaced values.

In [68]:
f = np.arange(10,50,5)   # Create an array of values starting at 10 in increments of 5
print(f)

[10 15 20 25 30 35 40 45]


Note this ends on 45, not 50 (does not include the top end of the
interval).

In [17]:
import numpy as np
g = np.linspace(0., 1., num=5)
print(g)


[0.   0.25 0.5  0.75 1.  ]


Sometimes, we may want to construct an array from existing arrays by
“stacking” the existing arrays, either vertically or horizontally. We
can use `vstack()` (or `row_stack`) and `hstack()` (or `column_stack`),
respectively.

In [73]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

### Indexing and Slicing

We can index and slice numpy arrays in all the ways we can slice Python
lists:

![](http://jalammar.github.io/images/numpy/numpy-array-slice.png)

And you can index and slice numpy arrays in multiple dimensions. If
slicing an array with more than one dimension, you should specify a
slice for each dimension:

![](http://jalammar.github.io/images/numpy/numpy-matrix-indexing.png)

Slicing return values by reference

In [75]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


updating value of b will update value of a

In [76]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


In [77]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:3, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[ 5  6  7  8]
 [ 9 10 11 12]] (2, 4)


Boolean array indexing: Boolean array indexing lets you pick out
arbitrary elements of an array. Frequently this type of indexing is used
to select the elements of an array that satisfy some condition. Here is
an example:

In [79]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [7]:
a = np.array([[3,1], [1, 3], [2, 7]])
data = a[a >= 3]
print(data)


[3 3 7]


### Math Functions

What makes working with `numpy` so powerful and convenient is that it
comes with many *vectorized* math functions for computation over
elements of an array. These functions are highly optimized and are
*very* fast - much, much faster than using an explicit `for` loop.

For example, let’s create a large array of random values and then sum it
both ways. We’ll use a `%%time` *cell magic* to time them.

In [11]:
a = np.random.random((2,2))
a

array([[0.34256065, 0.30036569],
       [0.45293751, 0.48591876]])

Look at the “Wall Time” in the output - note how much faster the
vectorized version of the operation is! This type of fast computation is
a major enabler of machine learning, which requires a *lot* of
computation.

Whenever possible, we will try to use these vectorized operations.

Some mathematic functions are available both as operator overloads and
as functions in the numpy module.

For example, you can perform an elementwise sum on two arrays using
either the + operator or the `add()` function.

![](http://jalammar.github.io/images/numpy/numpy-arrays-adding-1.png)

![](http://jalammar.github.io/images/numpy/numpy-matrix-arithmetic.png)

In [82]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


And this works for other operations as well, not only addition:

![](http://jalammar.github.io/images/numpy/numpy-array-subtract-multiply-divide.png)

In [84]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [85]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


We use the `dot()` function to compute inner
products of vectors, to multiply a vector by a matrix, and to multiply
matrices. `dot()` is available both as a function in the numpy module
and as an instance method of array objects:

![](http://jalammar.github.io/images/numpy/numpy-matrix-dot-product-1.png)

In [93]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))





219
219


In [95]:
print(np.dot(x, y))

[[19 22]
 [43 50]]


Besides for the functions that overload operators, Numpy also provides
many useful functions for performing computations on arrays, such as
`min()`, `max()`, `sum()`, and others:

![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-1.png)

In [96]:
x = np.array([[1, 2], [3, 4], [5, 6]])

print(np.max(x)) 
print(np.min(x))  
print(np.sum(x)) 

6
1
21


Not only can we aggregate all the values in a matrix using these
functions, but we can also aggregate across the rows or columns by using
the `axis` parameter:

![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-4.png)

In [98]:
x = np.array([[1, 2], [5, 3], [4, 6]])

print(np.max(x, axis=0))  # Compute max of each column; prints "[5 6]"
print(np.max(x, axis=1))  # Compute max of each row; prints "[2 5 6]"

[5 6]
[2 5 6]


You can find the full list of mathematical functions provided by numpy
in the
[documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently
need to reshape or otherwise manipulate data in arrays. The simplest
example of this type of operation is transposing a matrix; to transpose
a matrix, simply use the T attribute of an array object.

![](http://jalammar.github.io/images/numpy/numpy-transpose.png)

In [99]:
x = np.array([[1, 2], [3, 4], [5, 6]])

print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]
 [5 6]]
transpose
 [[1 3 5]
 [2 4 6]]


# Exercises

* Create a 1D array of 20 random integers between 1 and 100.
* Reshape the above array into a 4x5 matrix.
* Extract the diagonal elements of a 4x4 identity matrix.
* Create a 2D array of shape (5, 5) with random integers between 0 and 9, and replace all even values with -1.
* Given two arrays a and b, find the common elements between them.
* Create a 5x5 matrix where each row is a repetition of the integers from 1 to 5.
* Calculate the matrix product of a 3x4 matrix and a 4x2 matrix.
* Create a 1D array of 1000 random values between 0 and 1.
* Generate a 10x10 identity matrix.
* Use numpy to shuffle the rows randomly in above task.

In [ ]:
# YOUR CODE HERE


## Read numbers.txt into a numpy array and perform following numpy operations
Read "numbers.txt" into a numpy array.

Find the product of the first and last elements in the array.

Calculate the sum of every alternate element in the array (starting from the first element).

Find the standard deviation of the elements in the array.

Create a new array that contains the square root of each element in the original array.

Count the number of elements equal to 10 in the array.

Sort the array in descending order.

Enlist pairs that sum upto a number greater than 14000

In [8]:
# Specify the file path
file_path = 'Numbers.txt'  # Replace with the actual file path

# Initialize an empty list to store the data
data = []

# Read the file line by line
with open(file_path, 'r') as file:
    for line in file:
        # Split the line into numbers, removing extra spaces
        numbers = line.strip().split()
        # Convert the numbers to float and append to the data list
        data.append([float(num) for num in numbers])

# Convert the data list to a NumPy array
data_array = np.array(data)

# Print the resulting 2D array
print(data_array)
print(data_array.shape)

[[7719. 7277. 1781. ... 3273. 2993. 3210.]]
(1, 400010)


In [ ]:
# YOUR CODE HERE
np.random.randint(100,size=20)